Feature/app structure
RomiKMoveo/Epicure-Frontend pull request #1
Opened 2024-05-11 13:06 UTC by RomiKMoveo

### Description
> Insert a brief description of the changes made in this pull request. What problem does this PR solve and/or what new features does it add?

Created the app's structure base on the recommended structure  of Moveo-Protocol-code for React.

### Changes Made
> Provide a detailed description of the changes made in this pull request. This can include code changes, bug fixes, and new features. Use bullet points or numbered lists to make it clear and easy to read.

Added home page, and the component that the home page render( the components are not implemented yet).
Added general style, colors, and typography as a basic layer of the app.
Added un-implemented button card and error components that can be reuse throughout  the app. 

### Related Issues
> If there are any related issues or pull requests, link them here. For example, if this pull request solves a bug that was reported in an issue, link to that issue.

none

### Checklist
> Put an x in the boxes that apply. If you're unsure about any of these, don't hesitate to ask for help.

I have:
- [ ] deleted all irrelevant comments, logs and debuggers.
- [ ] assure that I don't print full error stacks, full body response or headers from the server in the console.
- [ ] deleted all sensitive information from the code because it's being imported from environment variables.
- [ ] encrypted keys/passwords that are sent through the internet.
- [ ] sanitized all user inputs to prevent attacks.
- [ ] made sure my code is generic and reusable for future things or reused existing resources.
- [ ] made sure that my code is readable.
- [ ] checked that the functions and resource names are self-explanatory.
- [ ] tested the code locally and it works as expected.
- [ ] added validations and error handling in relevant cases (external requests, integrations, etc).

2024-05-11 14:23 UTC, MoranOshiaMoveo commented on epicure-frontend/src/pages/home/components/Hero/Hero.scss
> +    //flex-direction: column;
Delete comments

2024-05-11 14:24 UTC, MoranOshiaMoveo requested changes

2024-05-11 14:24 UTC, MoranOshiaMoveo commented on epicure-frontend/src/pages/home/components/IconsMeaning/IconsMeaning.scss
> +    //flex-direction: column;
Delete

2024-05-11 14:24 UTC, MoranOshiaMoveo commented on epicure-frontend/src/shared/components/Button/Button.scss
> +  //@include flex-container( row, center, center );
Delete

2024-05-11 14:25 UTC, MoranOshiaMoveo requested changes
Pls noticed that u'll setting node modules in to git ignore it is not supposed to be in the uploaded files

2024-05-12 06:56 UTC, RomiKMoveo commented on epicure-frontend/src/pages/home/components/Hero/Hero.scss
> +    //flex-direction: column;
done

2024-05-12 06:57 UTC, RomiKMoveo commented on epicure-frontend/src/pages/home/components/IconsMeaning/IconsMeaning.scss
> +    //flex-direction: column;
delete

2024-05-12 06:59 UTC, RomiKMoveo commented on epicure-frontend/src/shared/components/Button/Button.scss
> +  //@include flex-container( row, center, center );
done

2024-05-12 07:13 UTC, MoranOshiaMoveo approved these changes

2024-05-12 07:18 UTC, merged