Feature/cards
RomiKMoveo/Epicure-Frontend pull request #7
Opened 2024-05-19 11:00 UTC by RomiKMoveo

### Description
> Insert a brief description of the changes made in this pull request. What problem does this PR solve and/or what new features does it add?

created a generic card component and adjust it to 3 different styles.

### Changes Made
> Provide a detailed description of the changes made in this pull request. This can include code changes, bug fixes, and new features. Use bullet points or numbered lists to make it clear and easy to read.

created a generic card component.
created 3 components that use the generic card component.

### Related Issues
> If there are any related issues or pull requests, link them here. For example, if this pull request solves a bug that was reported in an issue, link to that issue.

none.

### Checklist
> Put an x in the boxes that apply. If you're unsure about any of these, don't hesitate to ask for help.

I have:
- [ ] deleted all irrelevant comments, logs and debuggers.
- [ ] assure that I don't print full error stacks, full body response or headers from the server in the console.
- [ ] deleted all sensitive information from the code because it's being imported from environment variables.
- [ ] encrypted keys/passwords that are sent through the internet.
- [ ] sanitized all user inputs to prevent attacks.
- [ ] made sure my code is generic and reusable for future things or reused existing resources.
- [ ] made sure that my code is readable.
- [ ] checked that the functions and resource names are self-explanatory.
- [ ] tested the code locally and it works as expected.
- [ ] added validations and error handling in relevant cases (external requests, integrations, etc).

2024-05-19 11:35 UTC, MoranOshiaMoveo requested changes

2024-05-19 11:35 UTC, MoranOshiaMoveo commented on epicure-frontend/src/shared/components/Button/Button.scss
> +    height: 1000px;
why needed ?

2024-05-19 11:35 UTC, MoranOshiaMoveo commented on epicure-frontend/src/pages/home/components/Restaurant/Restaurant.tsx
> +        <Button text="All Restaurants" height="35px" icon={allCardsIcon} color="primary-color-black" backGroundColor=" var(--transparent-color)" onClick={handleClick} children={undefined} ></Button>
it seems that u dont need the children

2024-05-20 05:53 UTC, RomiKMoveo commented on epicure-frontend/src/pages/home/components/Restaurant/Restaurant.tsx
> +        <Button text="All Restaurants" height="35px" icon={allCardsIcon} color="primary-color-black" backGroundColor=" var(--transparent-color)" onClick={handleClick} children={undefined} ></Button>
done

2024-05-20 06:11 UTC, RomiKMoveo commented on epicure-frontend/src/shared/components/Button/Button.scss
> +    height: 1000px;
done

2024-05-20 06:12 UTC, merged